@startuml

actor Klient
actor Kasjer



Klient -> Kasjer : powitanie
return 
Klient -> Kasjer : miejsce, termin
Kasjer -> System : wyszukiwanie_polaczeń(miejsce, termin)
activate System
return polaczenie
Kasjer --> Klient: polaczenie
Klient -> Kasjer : potwierdzenie zakupu
Kasjer -> System : sprzedarz_biletu(polaczenie)
activate System
System -> System : rzerwacja_biletu(polaczenie, Klient)
activate System
return
System --> Kasjer : bilet

deactivate System

Kasjer -> Klient : forma płatności
'dodać aktwacje poniżej
alt płatność kartą 
    return płatność karta
    Kasjer -> Kasa : kwota, karta
    activate Kasa
    Kasa -> Terminal : kwota
    activate Terminal
    Terminal -> Klient : podaj pin
    Klient --> Terminal : pin 

    entity Bank
    Terminal -> Bank : autoryzacja 
    Bank --> Terminal : accept
    return accept
    return : ok
    ' Dodać wydrukowanie biletu i paragonu
    Kasjer --> Klient: bilet, paragon, potwierdzenie

else płatność gotówką
    Kasjer -> Kasa : kwota, karta
    activate Kasa
    return : ok
    ' Dodać wydrukowanie biletu i paragonu
    Kasjer --> Klient: bilet, paragon, potwierdzenie
end

@enduml
