@startuml

actor Klient
actor Kasjer

Klient -> Kasjer : miejsce, termin

Kasjer -> SystemPkp : wyszukanieTrasy(miejsce, termin)
activate SystemPkp
database "Baza Danych" as DB 
SystemPkp -> DB : query
activate DB
return 
return połączenia
Kasjer --> Klient: połączenia
Klient -> Kasjer: połączenie 

Kasjer -> Klient : forma zapłaty
alt : płatność gotówką
    Klient -> Kasjer : płatność gotówką
    Kasjer -> SystemPkp : zakupBiletu(połączenie)
    activate SystemPkp
    SystemPkp -> Kasa : wpłata (kwota)
    activate Kasa
    Kasa -> Kasjer : czy zapłacono
    Kasjer --> Kasa : tak, kwota
    Kasa -> Kasa : zmianaStanu(kwota)
    Kasa -> Drukarka : wydruk(bilet, paragon)
    activate Drukarka
    return
    return bilet, paragon
    SystemPkp -> DB: logowanie operacji
    activate DB
    return
    return zapłacono, bilet, paragon
    Kasjer --> Klient : bilet, paragon

else : płatność kartą
    Klient -> Kasjer : płatność kartą
    Kasjer -> SystemPkp : zakupBiletu(połączenie)
    activate SystemPkp
    SystemPkp -> Kasa : wpłata (kwota, karta)
    activate Kasa
    Kasa -> Terminal : wpłata(kwota)
    activate Terminal
    Terminal -> Klient : zatwierdź
    Klient --> Terminal : pin
    boundary Bank 
    Terminal -> Bank : autoryzacja
    Bank --> Terminal : ok
    return ok
    Kasa -> Kasa : zmianaStanu(kwota)
    Kasa -> Drukarka : wydruk(bilet, paragon, potwierdzenie)
    activate Drukarka
    return 
    return bilet, paragon, potwierdzenie
    SystemPkp -> DB: logowanie operacji
    DB --> SystemPkp
    return : zapłacono
    Kasjer --> Klient : bilet, paragon
end



@enduml